FROM node:14.15.5-alpine as build-step

RUN mkdir -p /app

WORKDIR /app

COPY angular/package.json /app

RUN npm install

COPY angular/. /app

RUN npm run build --prod

#Segunda Etapa
FROM nginx:1.17.1-alpine
COPY --from=build-step /app/dist/angular/. /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]